name: Build and Release .NET CLI App

on:
  push:
  #  tags:
  #    - 'v*.*.*'  # Triggers on version tag push
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and Publish project
      run: dotnet publish -r win-x64
    - name: Copy to package directory
      shell: cmd
      run: |
        move /y bin\Release\net8.0-windows\win-x64 package
        copy eye-saver.ico package
        del /q package\publish
    - name: Compile .ISS to .EXE Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
      with:
        path: setup.iss
        options: /O.
    - name: Archive installer
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: eyesaver-installer.exe
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    - name: Upload Eye Saver Installer to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: eyesaver-installer.exe
        asset_name: eyesaver-installer.exe
        asset_content_type: application/octet-stream

