name: Build and Release .NET CLI App

on:
  push:
  #  tags:
  #    - 'v*.*.*'  # Triggers on version tag push
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        #cache: true
    - name: Restore dependencies
      run: dotnet restore

