name: Build and Release .NET CLI App

on:
  push:
  #  tags:
  #    - 'v*.*.*'  # Triggers on version tag push
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and Publish project
      run: dotnet publish -r win-x64
    - name: Copy to package directory
      shell: cmd
      run: |
        move /y bin\Release\net8.0-windows\win-x64 package
        copy eye-saver.ico package
        del /q package\publish
    - name: Compile .ISS to .EXE Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
      with:
        path: setup.iss
        options: /O.